/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import ChessBoard from "~/components/Chess/chesboard";
import useBreakPoints from "~/hooks/useBreakPoints";

const Home: NextPage = () => {
  const {s} = useBreakPoints();

  return (
    <>
      <Head>
        <title>Chess</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={"flex min-h-screen flex-col items-center sm:mt-40 md:mt-32 lg:mt-20 xl:mt-12 2xl:mt-10"}>
        <div className="container flex flex-col items-center justify-center px-4">
          <ChessBoard width={s([300, 400, 500, 500, 450])} />
        </div>

      </main>
    </>
  );
};

export default Home;

