/* eslint-disable @typescript-eslint/no-unsafe-assignment */
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import ChessBoard from "~/components/Chess/chesboard";
import useBreakPoints from "~/hooks/useBreakPoints";
import {useSubscription} from "~/hooks/useSubscription";

const Home: NextPage = () => {
  const {s} = useBreakPoints();
  const [test, setTest] = useState<{test: number}>({
    test: 0
  });
  useSubscription("test", "test", setTest);

  return (
    <>
      <Head>
        <title>Chess</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <div className="container flex flex-col items-center justify-center gap-12 px-4 py-16 ">
          <ChessBoard width={s([100, 0, 300, 0, 300])} />
        </div>
        <div>
          {test?.test}
        </div>
      </main>
    </>
  );
};

export default Home;

