import { type NextPage } from "next";
import Head from "next/head";

import { api } from "~/utils/api";

const Puzzles: NextPage = () => {
  

  return (
    <>
      <Head>
        <title>Puzzles</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
   
      </main>
    </>
  );
};

export default Puzzles;

