import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { SignOutButton } from "@clerk/nextjs";

import { api } from "~/utils/api";

const Settings: NextPage = () => {

  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">

      </main>
    </>
  );
};

export default Settings;

