/* eslint-disable @typescript-eslint/no-misused-promises */
import { type NextPage } from "next";
import Head from "next/head";
import { useClerk } from "@clerk/clerk-react";
import { api } from "~/utils/api";
import useBreakPoints from "~/hooks/useBreakPoints";

const Settings: NextPage = () => {
  const {signOut} = useClerk(); 
  const {data} = api.users.userProfile.useQuery();
  const {s} = useBreakPoints(); 

  return (
    <>
      <Head>
        <title>Settings</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center">
        <div className={"card card-side bg-neutral shadow-xl mt-10"}>
          <figure><img loading="lazy" src="/test.jpg" alt="Profile Image"/></figure>
          <div className="card-body">
            <h2 className="card-title">Profile</h2>
            <p> {data?.name || "Username"} </p>
            <p> {data?.email || "User Email"} </p>
            <p> MMR: 3000 </p>
            <div className="card-actions justify-end">
              <button onClick={() => signOut()} className="btn btn-primary">
                Sign Out
              </button>
            </div>
          </div>
        </div>
      </main>
    </>
  );
};

export default Settings;

